// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DoINeedToInstall() {
  return window['go']['main']['App']['DoINeedToInstall']();
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function Patch(arg1, arg2, arg3) {
  return window['go']['main']['App']['Patch'](arg1, arg2, arg3);
}

export function Read() {
  return window['go']['main']['App']['Read']();
}

export function StartGDPS(arg1, arg2) {
  return window['go']['main']['App']['StartGDPS'](arg1, arg2);
}
