// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function Patch(arg1, arg2) {
  return window['go']['main']['App']['Patch'](arg1, arg2);
}

export function Read() {
  return window['go']['main']['App']['Read']();
}
